"""add date to meetings table

Revision ID: 9f68b57b8586
Revises: 8167e0c39871
Create Date: 2025-09-14 17:13:34.865822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f68b57b8586'
down_revision: Union[str, Sequence[str], None] = '8167e0c39871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'date')
    # ### end Alembic commands ###
